# Generated by Django 4.0.1 on 2022-01-12 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_refreshtoken_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('expire', models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 28, 47, 488236, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ListIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('expire', models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 57, 35, 486232, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
